query folio {
  about(where: { slug: "thomas-thorstensson" }) {
    name
    bioTitle
    bio
    aboutHeroTitle
    aboutHeroDesc
    aboutTitle
    aboutDesc
    jobTitle
    job
    timelineItem
    codeTitle
    codeOneTitle
    codeOneDesc
    codeTwoTitle
    codeTwoDesc
    codeThreeTitle
    codeThreeDesc
    picture {
      id
    }
  }

  intro(where: { slug: "intros" }) {
    heroIntroTitle
    heroIntroDesc
    aboutIntroTitle
    aboutIntroDesc
    projIntroTitle
    projIntroDesc
    knowIntroTitle
    knowIntroDesc
    knowOneTitle
    knowOneDesc
    knowTwoTitle
    knowTwoDesc
    knowThreeTitle
    knowThreeDesc
    metaIntroTitle
    metaIntroDesc
    metaTechTitle
    metaTechDesc
    metaCreativeTitle
    metaCreativeDesc
    metaIdeTitle
    metaIdeDesc
    metaPublishTitle
    metaPublishDesc
    blogTitle
    blogDesc
    blogExcerptsTitle
    blogExcerptsDesc
    blogExcerptsQuote
  }

  projects {
    name
    client
    endclient
    date
    duration
    type
    demo
    description
    id
    sourceCode
    slug
    tags
    synop
    testimonialName
    testimonialAgency
    testimonialText
    labUrl
    image {
      id
      handle
      fileName
    }
  }

  contact(where: { slug: "contact" }) {
    id
    viewHeroTitle
    viewHeroCta
    emailTitle
    email
    address
    addressTitle
  }
}
