query folio {
  about(where: { slug: "thomas-thorstensson" }) {
    name
    bioTitle
    bio
    aboutHeroTitle
    aboutHeroDesc
    aboutTitle
    aboutDesc
    jobTitle
    job
    valueOneTitle
    valueOneDesc
    valueTwoTitle
    valueTwoDesc
    valueThreeTitle
    valueThreeDesc
    picture {
      id
    }
  }

  intro(where: { slug: "intros" }) {
    heroIntroTitle
    heroIntroDesc
    aboutIntroTitle
    aboutIntroDesc
    projIntroTitle
    projIntroDesc
    techIntroTitle
    techIntroDesc
    techOneTitle
    techOneDesc
    techTwoTitle
    techTwoDesc
    techThreeTitle
    techThreeDesc
    metaTechTitle
    metaTechDesc
    metaCreativeTitle
    metaCreativeDesc
    metaIdeTitle
    metaIdeDesc
    metaPublishTitle
    metaPublishDesc
  }

  projects {
    name
    client
    endclient
    date
    demo
    description
    id
    sourceCode
    slug
    tags
    synop
    testimonialName
    testimonialAgency
    testimonialText
    image {
      id
      handle
      fileName
    }
  }
}
